apiVersion: v1
kind: Secret
metadata:
  name: gitlab-auth
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://gitlab.hosts.local/42/wil
  username: root
  password: glpat-YqKsnFgcJYoLBLBDap2j
