apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wil
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "http://10.43.116.61:8181/root/wil.git/"
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true