global:
  edition: ce
  hosts:
    domain: hosts.local
    https: false
  ingress:
    configureCertmanager: false
    enabled: true
    class: "nginx"
  initialRootPassword:
    secret: gitlab-initial-root-password
    key: password

nginx-ingress:
  enabled: false

certmanager:
  install: false

gitlab-runner:
  install: false

prometheus:
  install: false

postgresql:
  persistence:
    size: 500Mi

redis:
  master:
    persistence:
      size: 500Mi

gitaly:
  persistence:
    size: 1Gi

minio:
  install: false