Vagrant.configure("2") do |config|
  # OS
  config.vm.box = "ubuntu/jammy64"

  # Setup the server
  config.vm.define "userS" do |server|
    # Setting name of container, networking
    server.vm.hostname = "userS"
    server.vm.network "private_network", ip: "192.168.56.110"

    # Resources
    if Vagrant::Util::Platform.mac?
      server.vm.provider "parallels" do |prl|
        prl.memory = 1024
        prl.cpus = 1
      end
    else
      server.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
        vb.cpus = 1
      end
    end

    # Execute the script directly
    server.vm.provision "shell", path: "scripts/setup.sh"
    server.vm.provision "shell", path: "scripts/deploy.sh"
  end

end
