Vagrant.configure("2") do |config|
  # OS
  config.vm.box = "ubuntu/jammy64"

  # Setup the server
  config.vm.define "userS" do |server|
    # Setting name of container, networking
    server.vm.hostname = "userS"
    server.vm.network "private_network", ip: "192.168.56.110"

    # Resources
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end

    # Execute the script directly
    server.vm.provision "shell", path: "scripts/setup.sh"
    server.vm.provision "shell", path: "scripts/deploy.sh"
  end

end
