Vagrant.configure("2") do |config|
  # OS
  config.vm.box = "debian/bullseye64"

  # Setup the server
  config.vm.define "bghandriS" do |server|
    # Setting name of container, networking
    server.vm.hostname = "bghandriS"
    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = 4
    end

    # Execute the script directly
    server.vm.provision "shell", path: "scripts/setup.sh"
    server.vm.provision "shell", path: "scripts/deploy.sh"
  end

end
