Vagrant.configure("2") do |config|
  # OS
  config.vm.box = "ubuntu/jammy64"

  # Give my sshkey to the vm
  config.ssh.insert_key = true

  # Setup the server
  config.vm.define "userS" do |server|
    # Setting name of container, networking
    server.vm.hostname = "userS"
    server.vm.network "private_network", ip: "192.168.56.110"

    # Resources
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end

    # Copy the file in the vm
    server.vm.provision "file", source: "scripts/server.sh", destination: "/tmp/server.sh"

    # Execute the script
    server.vm.provision "shell", inline: "sh /tmp/server.sh"
  end
  
  # Setup the worker
  config.vm.define "userSW" do |worker|
    # Setting name of container, networking
    worker.vm.hostname = "userSW"
    worker.vm.network "private_network", ip: "192.168.56.111"

    # Resources
    worker.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end

    # Copy the file in the vm
    worker.vm.provision "file", source: "scripts/worker.sh", destination: "/tmp/worker.sh"

    # Execute the script
    worker.vm.provision "shell", inline: "sh /tmp/worker.sh"
  end
end
