Vagrant.configure("2") do |config|
  # OS
  config.vm.box = "debian/bullseye64"

  # Setup the server
  config.vm.define "sredjiniS" do |server|
    # Setting name of container, networking
    server.vm.hostname = "sredjiniS"
    server.vm.network "private_network", ip: "192.168.56.110"

    # Resources
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = 4
    end

    # Execute the script directly
    server.vm.provision "shell", path: "scripts/server.sh"
  end
  
  # Setup the worker
  config.vm.define "sredjiniSW" do |worker|
    # Setting name of container, networking
    worker.vm.hostname = "sredjiniSW"
    worker.vm.network "private_network", ip: "192.168.56.111"

    # Resources
    worker.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end

    # Execute the script directly
    worker.vm.provision "shell", path: "scripts/worker.sh"
  end
end
