Vagrant.configure("2") do |config|
  config.vm.define "userS" do |server|
    server.vm.box = "ubuntu/jammy64"
    server.vm.hostname = "userS"
    server.vm.network "private_network", ip: "192.168.56.110"
    
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end

    server.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update -y
      sudo apt-get install -y curl
      curl -sfL https://get.k3s.io | sh -
      mkdir -p $HOME/.kube
      sudo cp /etc/rancher/k3s/k3s.yaml $HOME/.kube/config
      sudo chown $(whoami):$(whoami) $HOME/.kube/config
      echo "K3s Server setup complete!"
    SHELL
  end

  config.vm.define "userSW" do |worker|
    worker.vm.box = "ubuntu/jammy64"
    worker.vm.hostname = "userSW"
    worker.vm.network "private_network", ip: "192.168.56.111"

    worker.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end

    worker.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update -y
      sudo apt-get install -y curl
      K3S_TOKEN=$(ssh -o StrictHostKeyChecking=no vagrant@192.168.56.110 "sudo cat /var/lib/rancher/k3s/server/node-token")
      curl -sfL https://get.k3s.io | K3S_URL="https://192.168.56.110:6443" K3S_TOKEN="$K3S_TOKEN" sh -
      echo "K3s Worker setup complete!"
    SHELL
  end
end
